config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get "home/about", to: "homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resources :book_comments, only: [:create, :destroy]  
   resource :favorite, only: [:create, :destroy]
  end 
  
  resources :users, only: [:index,:show,:edit,:update,:create] do
   resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
  	 get "followers" => "relationships#followers", as: "followers"
  end
  
  get "/search", to: "searches#search"

  resources :chats, only: [:show, :create, :destroy]
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :week_favorites, -> { where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day) }
  has_many :read_counts, dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
 def favorited_by?(user)
  favorites.exists?(user_id: user.id)
 end
  
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      Book.where('name LIKE ?', '%' + content)
    else
      Book.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

    def show
      @book = Book.find(params[:id])       # 書籍データを1回の検索で取得
      @user = @book.user                   # 書籍に関連するユーザーを取得
      @book_comment = BookComment.new      # コメント用のオブジェクトを作成
      
      # 過去に一度も閲覧していない場合に閲覧数を記録
      unless ReadCount.find_by(user_id: current_user.id, book_id: @book.id)
        current_user.read_counts.create(book_id: @book.id)
      end  
      
      # 今日の閲覧履歴がない場合に閲覧数を記録
      unless ReadCount.where(created_at: Time.zone.now.all_day).find_by(user_id: current_user.id, book_id: @book.id)
        current_user.view_counts.create(book_id: @book.id)
      end  
    end

  def index
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
  
    @books = Book.left_joins(:favorites)  # favoritesとのLEFT JOINを使用
                 .group('books.id')        # books.idでグループ化
                 .order('COUNT(favorites.id) DESC')  # いいねの数で降順に並べ替え
  
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render 'index', notice: "You have updated book successfully."
    end
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path, alert: "You are not authorized to edit or delete this book."
    end
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_edit_book.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit "Editing Book", class: 'btn btn-success' %>
 </div>
<% end %>

app/views/books/_favorite.html.erb
<% if current_user.favorites.exists?(book_id: book.id) %>
   <%= link_to book_favorite_path(book), method: :delete do %>
    ♥<%= book.favorites.count %>
   <% end %>
<% else %>
   <%= link_to book_favorite_path(book), method: :post do %>
    ♡<%= book.favorites.count %>
   <% end %>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: Book.new,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class: 'btn btn-success' %>
 </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <% if book.user.present? %>
            <%= link_to(book.user) do %>
              <%= image_tag book.user.get_profile_image, size: '50x50' %>
            <% end %>
          <% else %>
            <p>No User</p>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
        <td id="favorite_btn_<%= book.id %>">
         <%= render "favorites/btn", book: book %>
        <td id = "comment_counter<%= book.id %>">
         <%= render "book_comments/counter", book: book %>
        </td>
        <td>閲覧数: <%= book.read_counts.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  	    <%= render 'layouts/errors', obj: @book %>
        <%= render 'form', book: @book %>
  		<%= render 'edit_book', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
   <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
      
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
   <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
     <h2>Book detail</h2>
  	   <table class='table'>
  		<tbody>
  		 <tr>
           <td><%= link_to(@user) do %>
            <%= image_tag @user.profile_image, size:"50x50" %><br>
            <%= @user.name %>
            <% end %>
           </td>
           <td><%= link_to @book.title, @book %></td>
           <td><%= @book.body %></td>
            #<!--いいね機能の非同期化-->
           <td id="favorite_btn_<%= @book.id %>">
            <%= render "favorites/btn", book: @book %>
           </td>
           # <!--コメント件数機能の非同期化-->
           <td id = "comment_counter<%= @book.id %>"> 
            <%= render "book_comments/counter", book: @book %>
           </td>
           <td>閲覧数: <%= @book.read_counts.count %></td>
             <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
           <% end %>
          </tr>
        </tbody>
      </table>
      
       <div id= "comment_index">
         <%= render "book_comments/index", book: @book %>
       </div>
      <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>